/**:
  ros__parameters:
    video_device: "/dev/video2"
    framerate: 30.0
    io_method: "mmap"
    frame_id: "dabai_dc1_color_optical_frame"
    pixel_format: "yuyv2rgb"
    av_device_format: "YUYV"
    image_width: 640
    image_height: 480
    camera_name: "dabai_dc1"
    camera_info_url: "file:///home/joey/piperx_humble_ws/config/dabai_dc1_camera_info.yaml"
    brightness: -1
    contrast: -1
    saturation: -1
    sharpness: -1
    gain: -1
    auto_white_balance: true
    white_balance: 4000
    autoexposure: true
    exposure: 100
    autofocus: false
    focus: -1
